# Generated by Django 3.0.5 on 2020-12-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app16', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
